/**
 * Mock rows for the Dynamics-style list view prototype.
 * Entity: property developments (primary key remains `studentId` for app routing compatibility).
 */
export const mockStudents = [
  {
    studentId: "DEV-10001",
    fullName: "Harbor Point Residences",
    location: "Bristol Harbour, UK",
    region: "South West England",
    status: "Planning",
    totalUnits: 120,
    ownerName: "Morgan Blake",
    createdOn: new Date("2026-01-08T10:00:00.000Z"),
  },
  {
    studentId: "DEV-10002",
    fullName: "Cedar Lane Townhomes",
    location: "Reading, Berkshire, UK",
    region: "South East England",
    status: "Active",
    totalUnits: 64,
    ownerName: "Priya Shah",
    createdOn: new Date("2026-01-14T14:20:00.000Z"),
  },
  {
    studentId: "DEV-10003",
    fullName: "Riverside Quarter Phase 2",
    location: "Manchester City Centre, UK",
    region: "North West England",
    status: "Active",
    totalUnits: 210,
    ownerName: "James Okonkwo",
    createdOn: new Date("2026-01-22T09:15:00.000Z"),
  },
  {
    studentId: "DEV-10004",
    fullName: "Summit View Apartments",
    location: "Edinburgh, Scotland, UK",
    region: "Scotland",
    status: "Planning",
    totalUnits: 88,
    ownerName: "Elena Vasquez",
    createdOn: new Date("2026-02-01T11:40:00.000Z"),
  },
  {
    studentId: "DEV-10005",
    fullName: "Oakwood Gardens",
    location: "Guildford, Surrey, UK",
    region: "South East England",
    status: "Completed",
    totalUnits: 42,
    ownerName: "Neil Smith",
    createdOn: new Date("2025-08-10T08:00:00.000Z"),
  },
  {
    studentId: "DEV-10006",
    fullName: "Meridian Wharf",
    location: "Cardiff Bay, UK",
    region: "Wales",
    status: "Active",
    totalUnits: 156,
    ownerName: "Frank Brooks",
    createdOn: new Date("2026-02-18T16:05:00.000Z"),
  },
  {
    studentId: "DEV-10007",
    fullName: "Kingswood Parc",
    location: "Leeds, West Yorkshire, UK",
    region: "Yorkshire & Humber",
    status: "Planning",
    totalUnits: 95,
    ownerName: "Morgan Blake",
    createdOn: new Date("2026-02-26T13:30:00.000Z"),
  },
  {
    studentId: "DEV-10008",
    fullName: "Lakeside Mews",
    location: "Cambridge, UK",
    region: "East of England",
    status: "Active",
    totalUnits: 36,
    ownerName: "Priya Shah",
    createdOn: new Date("2026-03-02T10:12:00.000Z"),
  },
  {
    studentId: "DEV-10009",
    fullName: "Station Yard Lofts",
    location: "Birmingham Digbeth, UK",
    region: "West Midlands",
    status: "Planning",
    totalUnits: 74,
    ownerName: "James Okonkwo",
    createdOn: new Date("2026-03-05T09:50:00.000Z"),
  },
  {
    studentId: "DEV-10010",
    fullName: "Greenfield Commons",
    location: "Exeter, Devon, UK",
    region: "South West England",
    status: "Completed",
    totalUnits: 58,
    ownerName: "Elena Vasquez",
    createdOn: new Date("2025-11-20T12:00:00.000Z"),
  },
  {
    studentId: "DEV-10011",
    fullName: "Northgate Studios",
    location: "Newcastle upon Tyne, UK",
    region: "North East England",
    status: "Active",
    totalUnits: 102,
    ownerName: "Neil Smith",
    createdOn: new Date("2026-03-11T15:22:00.000Z"),
  },
  {
    studentId: "DEV-10012",
    fullName: "Willowbrook Terrace",
    location: "Oxford, UK",
    region: "South East England",
    status: "Planning",
    totalUnits: 28,
    ownerName: "Frank Brooks",
    createdOn: new Date("2026-03-14T08:45:00.000Z"),
  },
  {
    studentId: "DEV-10013",
    fullName: "Granite Works",
    location: "Aberdeen, Scotland, UK",
    region: "Scotland",
    status: "Active",
    totalUnits: 134,
    ownerName: "Morgan Blake",
    createdOn: new Date("2026-03-17T11:18:00.000Z"),
  },
  {
    studentId: "DEV-10014",
    fullName: "Southbank Reach",
    location: "London SE1, UK",
    region: "Greater London",
    status: "Planning",
    totalUnits: 320,
    ownerName: "Priya Shah",
    createdOn: new Date("2026-03-19T14:00:00.000Z"),
  },
  {
    studentId: "DEV-10015",
    fullName: "Hearthstone Village",
    location: "York, UK",
    region: "Yorkshire & Humber",
    status: "Completed",
    totalUnits: 76,
    ownerName: "James Okonkwo",
    createdOn: new Date("2025-09-03T09:30:00.000Z"),
  },
  {
    studentId: "DEV-10016",
    fullName: "Beacon Hill Flats",
    location: "Brighton & Hove, UK",
    region: "South East England",
    status: "Active",
    totalUnits: 54,
    ownerName: "Elena Vasquez",
    createdOn: new Date("2026-03-22T10:55:00.000Z"),
  },
  {
    studentId: "DEV-10017",
    fullName: "Elm Court",
    location: "Nottingham, UK",
    region: "East Midlands",
    status: "Planning",
    totalUnits: 48,
    ownerName: "Neil Smith",
    createdOn: new Date("2026-03-25T12:08:00.000Z"),
  },
  {
    studentId: "DEV-10018",
    fullName: "Quarry Fields",
    location: "Sheffield, UK",
    region: "Yorkshire & Humber",
    status: "Active",
    totalUnits: 92,
    ownerName: "Frank Brooks",
    createdOn: new Date("2026-03-28T09:40:00.000Z"),
  },
  {
    studentId: "DEV-10019",
    fullName: "Silverline Heights",
    location: "Liverpool Waterfront, UK",
    region: "North West England",
    status: "Completed",
    totalUnits: 188,
    ownerName: "Morgan Blake",
    createdOn: new Date("2025-12-01T16:25:00.000Z"),
  },
  {
    studentId: "DEV-10020",
    fullName: "Ashdown Close",
    location: "Bath, UK",
    region: "South West England",
    status: "Planning",
    totalUnits: 22,
    ownerName: "Priya Shah",
    createdOn: new Date("2026-04-02T13:15:00.000Z"),
  },
];
