/**
 * Mock Students rows for the Dynamics-style list view prototype.
 */
export const mockStudents = [
  {
    studentId: "STU-10001",
    fullName: "Jordan Williams",
    email: "jordan.williams@studentmail.edu",
    status: "Submitted",
    ownerName: "Neil Smith",
    createdOn: new Date("2026-01-15T09:30:00.000Z"),
  },
  {
    studentId: "STU-10002",
    fullName: "Samira Okonkwo",
    email: "s.okonkwo@studentmail.edu",
    status: "Accepted",
    ownerName: "Frank Brooks",
    createdOn: new Date("2026-02-02T11:05:00.000Z"),
  },
  {
    studentId: "STU-10003",
    fullName: "Liam Chen",
    email: "liam.chen@studentmail.edu",
    status: "Draft",
    ownerName: "Neil Smith",
    createdOn: new Date("2026-02-18T16:42:00.000Z"),
  },
  {
    studentId: "STU-10004",
    fullName: "Priya Desai",
    email: "priya.desai@studentmail.edu",
    status: "Submitted",
    ownerName: "Frank Brooks",
    createdOn: new Date("2026-03-01T08:12:00.000Z"),
  },
  {
    studentId: "STU-10005",
    fullName: "Noah Bergström",
    email: "n.bergstrom@studentmail.edu",
    status: "Rejected",
    ownerName: "Neil Smith",
    createdOn: new Date("2026-03-04T13:20:00.000Z"),
  },
  {
    studentId: "STU-10006",
    fullName: "Emily Foster",
    email: "emily.foster@studentmail.edu",
    status: "Submitted",
    ownerName: "Frank Brooks",
    createdOn: new Date("2026-03-09T10:00:00.000Z"),
  },
  {
    studentId: "STU-10007",
    fullName: "Marcus Webb",
    email: "marcus.webb@studentmail.edu",
    status: "Accepted",
    ownerName: "Neil Smith",
    createdOn: new Date("2026-03-10T15:33:00.000Z"),
  },
  {
    studentId: "STU-10008",
    fullName: "Aisha Rahman",
    email: "aisha.rahman@studentmail.edu",
    status: "Draft",
    ownerName: "Frank Brooks",
    createdOn: new Date("2026-03-11T09:15:00.000Z"),
  },
  {
    studentId: "STU-10009",
    fullName: "Daniel Park",
    email: "daniel.park@studentmail.edu",
    status: "Submitted",
    ownerName: "Elena Vasquez",
    createdOn: new Date("2026-03-12T14:22:00.000Z"),
  },
  {
    studentId: "STU-10010",
    fullName: "Sophia Müller",
    email: "sophia.muller@studentmail.edu",
    status: "Accepted",
    ownerName: "Neil Smith",
    createdOn: new Date("2026-03-14T09:48:00.000Z"),
  },
  {
    studentId: "STU-10011",
    fullName: "Hiro Tanaka",
    email: "h.tanaka@studentmail.edu",
    status: "Submitted",
    ownerName: "Frank Brooks",
    createdOn: new Date("2026-03-15T11:30:00.000Z"),
  },
  {
    studentId: "STU-10012",
    fullName: "Olivia Bennett",
    email: "o.bennett@studentmail.edu",
    status: "Draft",
    ownerName: "Elena Vasquez",
    createdOn: new Date("2026-03-17T08:55:00.000Z"),
  },
  {
    studentId: "STU-10013",
    fullName: "Mateo García",
    email: "mateo.garcia@studentmail.edu",
    status: "Submitted",
    ownerName: "James Okonkwo",
    createdOn: new Date("2026-03-18T16:10:00.000Z"),
  },
  {
    studentId: "STU-10014",
    fullName: "Chloe Nguyen",
    email: "chloe.nguyen@studentmail.edu",
    status: "Rejected",
    ownerName: "Neil Smith",
    createdOn: new Date("2026-03-20T13:45:00.000Z"),
  },
  {
    studentId: "STU-10015",
    fullName: "Ethan O'Sullivan",
    email: "ethan.osullivan@studentmail.edu",
    status: "Accepted",
    ownerName: "Frank Brooks",
    createdOn: new Date("2026-03-22T09:00:00.000Z"),
  },
  {
    studentId: "STU-10016",
    fullName: "Zara Hussain",
    email: "zara.hussain@studentmail.edu",
    status: "Submitted",
    ownerName: "James Okonkwo",
    createdOn: new Date("2026-03-24T10:25:00.000Z"),
  },
  {
    studentId: "STU-10017",
    fullName: "Benjamin Klein",
    email: "b.klein@studentmail.edu",
    status: "Draft",
    ownerName: "Elena Vasquez",
    createdOn: new Date("2026-03-26T15:18:00.000Z"),
  },
  {
    studentId: "STU-10018",
    fullName: "Isabella Romano",
    email: "i.romano@studentmail.edu",
    status: "Submitted",
    ownerName: "Neil Smith",
    createdOn: new Date("2026-03-28T11:00:00.000Z"),
  },
  {
    studentId: "STU-10019",
    fullName: "Kai Lindqvist",
    email: "kai.lindqvist@studentmail.edu",
    status: "Accepted",
    ownerName: "Frank Brooks",
    createdOn: new Date("2026-03-30T14:50:00.000Z"),
  },
  {
    studentId: "STU-10020",
    fullName: "Amara Okafor",
    email: "amara.okafor@studentmail.edu",
    status: "Submitted",
    ownerName: "James Okonkwo",
    createdOn: new Date("2026-04-02T09:35:00.000Z"),
  },
  {
    studentId: "STU-10021",
    fullName: "Lucas Andersson",
    email: "lucas.andersson@studentmail.edu",
    status: "Rejected",
    ownerName: "Elena Vasquez",
    createdOn: new Date("2026-04-05T16:05:00.000Z"),
  },
  {
    studentId: "STU-10022",
    fullName: "Maya Patel",
    email: "maya.patel@studentmail.edu",
    status: "Submitted",
    ownerName: "Neil Smith",
    createdOn: new Date("2026-04-07T10:20:00.000Z"),
  },
  {
    studentId: "STU-10023",
    fullName: "Tomás Silva",
    email: "tomas.silva@studentmail.edu",
    status: "Accepted",
    ownerName: "Frank Brooks",
    createdOn: new Date("2026-04-09T12:42:00.000Z"),
  },
  {
    studentId: "STU-10024",
    fullName: "Naomi Cohen",
    email: "naomi.cohen@studentmail.edu",
    status: "Draft",
    ownerName: "James Okonkwo",
    createdOn: new Date("2026-04-11T08:30:00.000Z"),
  },
];
