/**
 * Mock Sales Staff rows (Dynamics-style list; `staffId` is the primary key for routing).
 */
export const mockSalesStaff = [
  {
    staffId: "SLS-31001",
    name: "Amelia Hart",
    role: "Account Executive",
    assignedDevelopmentId: "DEV-10001",
    assignedDevelopmentName: "Harbor Point Residences",
    email: "a.hart@contoso.edu",
    createdOn: new Date("2025-08-12T09:00:00.000Z"),
  },
  {
    staffId: "SLS-31002",
    name: "Oliver Grant",
    role: "Regional Sales Lead",
    assignedDevelopmentId: "DEV-10003",
    assignedDevelopmentName: "Riverside Quarter Phase 2",
    email: "o.grant@contoso.edu",
    createdOn: new Date("2025-09-01T11:20:00.000Z"),
  },
  {
    staffId: "SLS-31003",
    name: "Zara Malik",
    role: "Sales Coordinator",
    assignedDevelopmentId: "DEV-10002",
    assignedDevelopmentName: "Cedar Lane Townhomes",
    email: "z.malik@contoso.edu",
    createdOn: new Date("2025-09-18T14:05:00.000Z"),
  },
  {
    staffId: "SLS-31004",
    name: "Theo Nakamura",
    role: "Account Executive",
    assignedDevelopmentId: "DEV-10006",
    assignedDevelopmentName: "Meridian Wharf",
    email: "t.nakamura@contoso.edu",
    createdOn: new Date("2025-10-03T08:45:00.000Z"),
  },
  {
    staffId: "SLS-31005",
    name: "Imogen Clarke",
    role: "Show Home Specialist",
    assignedDevelopmentId: "DEV-10004",
    assignedDevelopmentName: "Summit View Apartments",
    email: "i.clarke@contoso.edu",
    createdOn: new Date("2025-10-21T10:10:00.000Z"),
  },
  {
    staffId: "SLS-31006",
    name: "Ben Carter",
    role: "Aftercare Advisor",
    assignedDevelopmentId: "DEV-10005",
    assignedDevelopmentName: "Oakwood Gardens",
    email: "b.carter@contoso.edu",
    createdOn: new Date("2025-11-07T13:30:00.000Z"),
  },
  {
    staffId: "SLS-31007",
    name: "Freya Olsen",
    role: "Regional Sales Lead",
    assignedDevelopmentId: "DEV-10011",
    assignedDevelopmentName: "Northgate Studios",
    email: "f.olsen@contoso.edu",
    createdOn: new Date("2025-11-24T09:15:00.000Z"),
  },
  {
    staffId: "SLS-31008",
    name: "Jamal Rivers",
    role: "Account Executive",
    assignedDevelopmentId: "DEV-10014",
    assignedDevelopmentName: "Southbank Reach",
    email: "j.rivers@contoso.edu",
    createdOn: new Date("2025-12-09T15:50:00.000Z"),
  },
  {
    staffId: "SLS-31009",
    name: "Hannah Doyle",
    role: "Sales Coordinator",
    assignedDevelopmentId: "DEV-10016",
    assignedDevelopmentName: "Beacon Hill Flats",
    email: "h.doyle@contoso.edu",
    createdOn: new Date("2026-01-14T12:00:00.000Z"),
  },
  {
    staffId: "SLS-31010",
    name: "Ryan Patel",
    role: "Account Executive",
    assignedDevelopmentId: "DEV-10019",
    assignedDevelopmentName: "Silverline Heights",
    email: "r.patel@contoso.edu",
    createdOn: new Date("2026-02-02T08:25:00.000Z"),
  },
  {
    staffId: "SLS-31011",
    name: "Nina Kowalski",
    role: "Show Home Specialist",
    assignedDevelopmentId: "DEV-10008",
    assignedDevelopmentName: "Lakeside Mews",
    email: "n.kowalski@contoso.edu",
    createdOn: new Date("2026-02-20T16:40:00.000Z"),
  },
  {
    staffId: "SLS-31012",
    name: "Chris Vaughan",
    role: "Aftercare Advisor",
    assignedDevelopmentId: "DEV-10013",
    assignedDevelopmentName: "Granite Works",
    email: "c.vaughan@contoso.edu",
    createdOn: new Date("2026-03-08T11:05:00.000Z"),
  },
];
