/**
 * Mock Staff rows for the Dynamics-style list view (same shape as used by StaffGrid).
 */
export const mockStaff = [
  {
    staffId: "STF-20001",
    name: "Elena Vasquez",
    role: "Administrator",
    department: "Office of the Registrar",
    email: "e.vasquez@contoso.edu",
    createdOn: new Date("2025-06-02T08:15:00.000Z"),
  },
  {
    staffId: "STF-20002",
    name: "Marcus Webb",
    role: "IT",
    department: "Information Technology Services",
    email: "m.webb@contoso.edu",
    createdOn: new Date("2025-07-11T10:40:00.000Z"),
  },
  {
    staffId: "STF-20003",
    name: "Priya Desai",
    role: "Finance",
    department: "Finance & Treasury",
    email: "p.desai@contoso.edu",
    createdOn: new Date("2025-08-19T14:05:00.000Z"),
  },
  {
    staffId: "STF-20004",
    name: "Noah Bergström",
    role: "Support",
    department: "Student Success Center",
    email: "n.bergstrom@contoso.edu",
    createdOn: new Date("2025-09-03T09:22:00.000Z"),
  },
  {
    staffId: "STF-20005",
    name: "Frank Brooks",
    role: "Administrator",
    department: "Academic Affairs",
    email: "f.brooks@contoso.edu",
    createdOn: new Date("2025-09-15T16:30:00.000Z"),
  },
  {
    staffId: "STF-20006",
    name: "Samira Okonkwo",
    role: "Finance",
    department: "Bursar & Student Accounts",
    email: "s.okonkwo@contoso.edu",
    createdOn: new Date("2025-10-01T11:50:00.000Z"),
  },
  {
    staffId: "STF-20007",
    name: "Liam Chen",
    role: "IT",
    department: "Infrastructure & Security",
    email: "l.chen@contoso.edu",
    createdOn: new Date("2025-10-22T13:10:00.000Z"),
  },
  {
    staffId: "STF-20008",
    name: "Aisha Rahman",
    role: "Support",
    department: "Admissions Operations",
    email: "a.rahman@contoso.edu",
    createdOn: new Date("2025-11-05T08:00:00.000Z"),
  },
  {
    staffId: "STF-20009",
    name: "Neil Smith",
    role: "Administrator",
    department: "College of Arts & Humanities",
    email: "n.smith@contoso.edu",
    createdOn: new Date("2025-11-18T15:45:00.000Z"),
  },
  {
    staffId: "STF-20010",
    name: "Jordan Williams",
    role: "Support",
    department: "Records & Registration",
    email: "j.williams@contoso.edu",
    createdOn: new Date("2025-12-02T12:18:00.000Z"),
  },
  {
    staffId: "STF-20011",
    name: "Sophia Müller",
    role: "Finance",
    department: "Grants & Contracts Accounting",
    email: "s.muller@contoso.edu",
    createdOn: new Date("2026-01-08T09:55:00.000Z"),
  },
  {
    staffId: "STF-20012",
    name: "Daniel Park",
    role: "IT",
    department: "Teaching & Learning Technologies",
    email: "d.park@contoso.edu",
    createdOn: new Date("2026-02-14T10:25:00.000Z"),
  },
];
